name: DockerTaurusContainer
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: blazemeter/taurus:latest
    steps:
      - name: Run Taurus Test
        run: |
          pwd
          docker container ls


