name: DailyGenixNotification
on: [push]
#on:
#  schedule:
#    - cron:  '30 15 * * *'

jobs:
  TriggerNotification:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Trigger DailyGenix Notification
        run: |
          jmeter -n -t .github/workflows/DailyGenixNotification.jmx
          echo "$now"
          echo "Notification Triggered"

