name: DockerTaurusContainer
on:
  schedule:
    - cron:  '30 15 * * *'

jobs:
  TriggerNotification:
    runs-on: ubuntu-latest
    container: blazemeter/taurus:latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger DailyGenix Notification
        run: |
          jmeter -n -t .github/workflows/DailyGenixNotification.jmx
          echo "Notification Triggered"

