name: DockerTaurusContainer
on: 

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: blazemeter/taurus:latest
    steps:
      - name: TriggerNotification
        run: |
          pwd
          docker container ls


