name: DGDatabase

on: [push]

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: blazemeter/taurus
    steps:
      - uses: actions/checkout@v2
      - name: multiline script
        run: |
          pwd
          #jmeter -n -t DailyGenixDatabase.jmx
          ls -a
          python3 --version
          

