name: GetDataAnyTime
on: [push]

#on: 
#  schedule:
#    - cron:  '30 15 * * *'
#    - cron:  '5 13 * * *'

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Databasescript
        run: |
          pwd
          #${JMETER_HOME}/lib
          ls -a
          apk update
          apk add python3-dev
          cp -a /__w/ApiTesting/ApiTesting/mysql-connector-java-5.1.12-bin.jar /opt/apache-jmeter-5.4.3/lib
          jmeter -n -t DailyGenixDatabase.jmx
          ls -a
          
      - name: triggerEmail
        run: |
          python3 DatabaseMailtriggerScript.py      

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataSheet
          path: |
            /__w/ApiTesting/ApiTesting

