name: DGDatabase

on: [push]

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: multiline script
        run: |
          sudo apt-get update
          sudo apt-get install python3.6
          pwd
          jmeter -n -t DailyGenixDatabase.jmx
          ls -a
          python3 --version
          

