name: DGDatabase1

on: [push]

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Database script
        run: |
          pwd
          #${JMETER_HOME}/lib
          ls -a
          cp -a /__w/ApiTesting/ApiTesting/mysql-connector-java-5.1.12-bin.jar /opt/apache-jmeter-5.4.3/lib
          #jmeter -n -t DailyGenixDatabase.jmx
          #pip install mysql-connector-python==8.0.11
          #bzt DatabaseQueryTriggerTaurus.yaml
          ls -a
          python3 --version
          

