name: GetDataAnyTime
#on: [push]

on: 
  workflow_dispatch:

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Databasescript
        run: |
          pwd
          #${JMETER_HOME}/lib
          ls -a
          apk update
          apk add python3-dev
          cp -a /__w/ApiTesting/ApiTesting/mysql-connector-java-5.1.12-bin.jar /opt/apache-jmeter-5.4.3/lib
          jmeter -n -t DailyGenixDatabase.jmx
          ls -a
       
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.gmail.com
          account: dailygenixauto@gmail.com
          password: H@rshsingh1305
          sender: DailyGgenix
          from: dailygenixauto@gmail.com
          to: harshdhiman01@gmail.com
          subject: GetOrderAnyTime
          body: PFA for File
          contentType: text/html
          attachments: getDataAnytime.csv
      #- name: triggerEmail
      #  run: |
      #    python3 DatabaseMailtriggerScript.py      

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataSheet
          path: |
            /__w/ApiTesting/ApiTesting

