name: DGDatabase1

on: [push]

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: blazemeter/taurus
    steps:
      - uses: actions/checkout@v2
      - name: Database script
        run: |
          pwd
          #jmeter -n -t DailyGenixDatabase.jmx
          #pip install mysql-connector-python==8.0.11
          bzt DatabaseQueryTriggerTaurus.yaml
          ls -a
          python3 --version
          

