name: GetDataAnyTime
#on: [push]

on: 
  workflow_dispatch:

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Databasescript
        run: |
          pwd
          #${JMETER_HOME}/lib
          ls -a
          apk update
          apk add python3-dev
          cp -a /__w/ApiTesting/ApiTesting/mysql-connector-java-5.1.12-bin.jar /opt/apache-jmeter-5.4.3/lib
          jmeter -n -t DailyGenixDatabase.jmx
          ls -a
          
      - name: Announcerr
        uses: singhkshitij/announcerr@v2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: dailygenixauto@gmail.com
          password: H@rshsingh1305
          subject: GetDataAnyTime
          # Literal body:
          #body: Just launched new version of my ${{github.repository}} ! It is fully packed with awesome features.
          # Read file contents as body:
          body: PFA for attachment
          to: harshdhiman01@gmail.com
          from: dailygenixauto@gmail.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: getDataAnytime.csv
       
      #- name: triggerEmail
      #  run: |
      #    python3 DatabaseMailtriggerScript.py      

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DataSheet
          path: |
            /__w/ApiTesting/ApiTesting

