name: DGDatabase1

on: [push]

jobs:
  runDatabaseQuery:
    runs-on: ubuntu-latest
    container: justb4/jmeter
    steps:
      - uses: actions/checkout@v2
      - name: Database script
        run: |
          pwd
          #${JMETER_HOME}/lib
          ls -a
          apk update
          apk add python3-dev
          cp -a /__w/ApiTesting/ApiTesting/mysql-connector-java-5.1.12-bin.jar /opt/apache-jmeter-5.4.3/lib
          jmeter -n -t DailyGenixDatabase.jmx
          #bzt DailyGenixDatabase.jmx
          ls -a
          #python3 --version
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            /__w/ApiTesting/ApiTesting

